FROM eclipse-temurin:21-jdk-alpine

ARG RDS_USER=${RDS_USER}
ENV RDS_USER=${RDS_USER}
ARG RDS_PASSWORD=${RDS_PASSWORD}
ENV RDS_PASSWORD=${RDS_PASSWORD}
ARG MONGO_USER=${MONGO_USER}
ENV MONGO_USER=${MONGO_USER}
ARG MONGO_PASSWORD=${MONGO_PASSWORD}
ENV MONGO_PASSWORD=${MONGO_PASSWORD}
ENV ENV_VARIABLES="-DRDS_USER=$RDS_USER -DRDS_PASSWORD=$RDS_PASSWORD -DMONGO_USER=$MONGO_USER -DMONGO_PASSWORD=$MONGO_PASSWORD"

WORKDIR /app
COPY target/appointment-system-*.jar appointment-system.jar
EXPOSE 8080
ENTRYPOINT java -jar ${ENV_VARIABLES} appointment-system.jar