server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/appointment-system
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3360/appointment_system
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@appointmentsystem.nrcqy4p.mongodb.net/?retryWrites=true
      database: appointments
    redis:
      host: redis-19366.c328.europe-west3-1.gce.redns.redis-cloud.com
      port: 19366
      username: default
      password: OmUE8ScGdV0VPif5Fq0m8dCZ9IVGNhZj
  cache:
      type: redis
  liquibase:
    change-log: classpath:db/changelog/master.xml

logging:
  level:
    org:
      springframework:
        web: INFO

jwt:
  auth:
    converter:
      resource-id: appointment-system-client
      principal-attribute: admin

keycloak:
  url: http://localhost:8088
  realm: appointment-system
  client-id: appointment-system-client
  client-secret: PeCq7P1Lm9RXpfJC4z9ru9edgeMwEyeg