name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      auto-version-bump:
        description: 'Should we bump the version?'
        required: true
        default: 'false'
      tags:
        description: 'Tags'

env:
  RDS_USER: '${{ secrets.RDS_USER }}'
  RDS_PASSWORD: '${{ secrets.RDS_PASSWORD }}'
  MONGO_USER: '${{ secrets.MONGO_USER }}'
  MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'

jobs:
  build:
    runs-on: [ubuntu-latest]
    environment:
      name: dev
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@v6
        with:
          github-token: ${{ secrets.DEPLOY_TOKEN }}
          git-committer: 'BOT'
          auto-version-bump: true
      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build --build-arg RDS_USER=$RDS_USER --build-arg RDS_PASSWORD=$RDS_PASSWORD --build-arg MONGO_USER=$MONGO_USER --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t renatokazinczi/appointment-system .
      - name: Publish image to docker hub
        run: docker push renatokazinczi/appointment-system:latest

  deploy:
    needs: build
    runs-on: [appointment-system-ec2]
    environment:
      name: dev
    steps:
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Pull Image from docker hub
      run: docker pull renatokazinczi/appointment-system:latest
    - name: Delete old container
      run: docker rm -f appointment-system
    - name: Run docker container
      run: docker run -d -p 8080:8080 --name appointment-system renatokazinczi/appointment-system
